"""Create agendamento table

Revision ID: bc4d0a3116dc
Revises: 0c36c7db6aaf
Create Date: 2025-04-01 16:23:43.465134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc4d0a3116dc'
down_revision = '0c36c7db6aaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agendamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=10), nullable=True),
    sa.Column('horario', sa.String(length=5), nullable=True),
    sa.Column('client', sa.String(length=100), nullable=True),
    sa.Column('servico', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agendamento')
    # ### end Alembic commands ###
